### DISCUSSION TITLE
Option to disable linking of step circles/text

### DISCUSSION THREAD

**Discussion by letmaik** [vueform/vueform#220] [Ideas]
It is possible to disable the previous button but navigation is still allowed through the circles with text at the top. It would be nice if the links of those could be disabled.

**Comment by adamberecz** [comment]
Thank you for the recommendation.

In the meantime you can add the following CSS to disable completed steps:
```css
/* Vueform theme */
.vf-step-completed {
  pointer-events: none;
}

/* Tailwind theme */
.form-step-completed {
  pointer-events: none;
}
```
